### ISSUE TITLE
mark - undefined

### ISSUE THREAD

**Issue by shinnokdisengir** [halt-hammerzeit/react-isomorphic-render#1]
Hi, i found this problem when I try to use the lib. Can u help me?
thanks,
gabriele

  TypeError: Cannot read property 'mark' of undefined
  
  - web server.js:39 start_web_server
    [TIPortal]/[react-isomorphic-render]/babel-transpiled-modules/page-server/web server.js:39:61
  
  - render.js:9 start
    render.js:9:5
  
  - web.js:36 
    web.js:36:29
  
  - es6.promise.js:89 run
    [TIPortal]/[core-js]/modules/es6.promise.js:89:22
  
  - es6.promise.js:102 
    [TIPortal]/[core-js]/modules/es6.promise.js:102:28
  
  - _microtask.js:18 flush
    [TIPortal]/[core-js]/modules/_microtask.js:18:9
  
  - next_tick.js:67 _combinedTickCallback
    internal/process/next_tick.js:67:7
  
  - next_tick.js:98 process._tickCallback
    internal/process/next_tick.js:98:9

  ---------

"devDependencies": {
    "autoprefixer-loader": "^3.2.0",
    "babel-cli": "^6.10.1",
    "babel-core": "^6.10.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-react-transform": "^2.0.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-plugin-typecheck": "^3.9.0",
    "babel-polyfill": "^6.9.1",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-node6": "^11.0.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-0": "^6.5.0",
    "babel-runtime": "^6.9.2",

**Comment by halt-hammerzeit** [comment]
The line is:

```
	var marked1$0 = [errors, rendering].map(_regeneratorRuntime.mark);
```

Which means that babel's "regenerator runtime" is `undefined`.
This may be because of different reasons.

What is your Node.js version?
You can try to update to the latest node.js.

**Comment by halt-hammerzeit** [comment]
Or maybe it's because this package uses `babel` runtime.
I'll add it to dependencies and release a new version.
Don't update your Node.js just yet.

**Comment by halt-hammerzeit** [comment]
Try `react-isomorphic-render@3.0.2`, it will install `babel-runtime` as a dependency

**Comment by shinnokdisengir** [comment]
ok, it's fixed. thanks
