### ISSUE TITLE
Trying to get the store before route creation

### ISSUE THREAD

**Issue by Vincz** [halt-hammerzeit/react-isomorphic-render#13]
Hi!

I'm trying to get the proper store in the create_routes function. I need to instanciate services before creating the routes in order to be able to use them in the Route callbacks (onEnter).
Basically, my routes callbacks need the store and additionnals services.
I tried to add some logics in the react-isomorphic-render file to be able to inject my services to the create_routes function and to the wrapper. Something like that:

    import { IntlProvider, addLocaleData } from 'react-intl';
    import frLocaleData                    from 'react-intl/locale-data/fr';
    addLocaleData(frLocaleData);

    import translations from './helpers/Translations';
    import { ListUrl, Seo, Api, References, Security } from 'services';

    import routes  from './routes'
    import Wrapper from './wrapper'

    const locale     = 'en';
    const host       = 'en';

    const client     = new Api();
    const messages   = translations(locale);
    const rel        = new IntlProvider({locale, messages, children: []}, {});
    const intl       = rel.getChildContext().intl;
    const references = new References();

    let services;

    export default
    {
        reducer: ()      => require('store/modules/reducer'),
        routes:  (store) => {
            const listUrl = new ListUrl(store, intl, references);
            const seo     = new Seo(intl, locale, host, listUrl);
            
            services = {listUrl, seo, intl, api: client, references};
            
            return routes(store, services.listUrl, api, intl);
        },
        wrapper: (props) => {

            const newProps = {
                ...props,
                services,
                locale,
                messages
            };

            return (<Wrapper {...newProps} />);
        },

        on_store_created({ reload_reducer }) {
            if (_development_ && module.hot) {
                module.hot.accept('./store/modules/reducer', reload_reducer)
            }
        }
    }

and my routes file looks like that:

    export default (store, listUrl, api, intl) => {
      const requireLogin     = hookAuth(store);
      const requireLogout    = hookNoAuth(store);
      const checkList        = hookList(store, listUrl, api);
      const checkItem        = hookItem(store, listUrl);
      const getComponentList = componentList(store, listUrl, api);

      const requireLoginAction = hookAuth(store, "actions");

      /**
       * Please keep routes in alphabetical order
       */
      return (
        <Route path="/" component={App}>
          <IndexRoute component={Home} />
          <Route component={Layout}>
            <Route path="login"    onEnter={requireLogout} component={Login} />
        

I don't know how to achieve this. I'd really like to move from react-isomorphic-tools to universal-webpack and your complete universal stack. Help would be really appreciate. Thanks !

**Comment by halt-hammerzeit** [comment]
Why don't you put the creation of your services into the `routes()` function?

```js
export default (store) => {
        const listUrl = new ListUrl(store, intl, references);
        const seo     = new Seo(intl, locale, host, listUrl);

        services = {listUrl, seo, intl, api: client, references};

        ...
}
```

Will it work for you?

**Comment by halt-hammerzeit** [comment]
Is your current approach working?
If not then how did you conclude that it's not working?

**Comment by Vincz** [comment]
I need this services in the wrapper as well.
The current approach is not working cause the store returned by the routes function is not the real store. 

    routes:  (store) => {  // bad store here

When i'm calling getState() on this store, i get an error at this line, telling me that action is not define.

https://github.com/halt-hammerzeit/react-isomorphic-render/blob/a2c7b0efc93d71716c2c78a9d1a8118322184c84/source/redux/store.js#L82

**Comment by halt-hammerzeit** [comment]
Oh, shoot, seems like a bug to me: there shouldn't be that `action` variable there. I'll fix that in a minute.

**Comment by halt-hammerzeit** [comment]
Try `npm install react-isomorphic-render@latest --save`

**Comment by halt-hammerzeit** [comment]
Ooops, there's still one little bug, it doesn't return anything.
Will fix.

**Comment by halt-hammerzeit** [comment]
Ok, version `4.1.7` should do it

**Comment by Vincz** [comment]
Thanks !! Solved my problem !! Great job :)
