### ISSUE TITLE
Allow more control on the http client

### ISSUE THREAD

**Issue by Vincz** [halt-hammerzeit/react-isomorphic-render#16]
I think it could be great to have one of the following option:
- Be able to manually set another "http client" instance (to include some logic)
- Have more control on the generated request and url formatter with callbacks or...

For example, in my project, i do have two api servers and they are not running on the same server as the webpage renderer or any other service. They have their own HTTP stack and i don't want to locally proxy to them.

**Comment by halt-hammerzeit** [comment]
> they are not running on the same server as the webpage renderer or any other service. They have their own HTTP stack and i don't want to locally proxy to them.

So how does your AJAX work then?

**Comment by Vincz** [comment]
By using CORS

**Comment by halt-hammerzeit** [comment]
So what exactly do you need?
You already can specify custom URL when performing requests:

`http.post("http://1.1.1.1/data")`

**Comment by halt-hammerzeit** [comment]
Oh, no, you can't

**Comment by halt-hammerzeit** [comment]
Well, I could add an option, say, `http.url(path) => URL`, which will be replacing `format_url()` if specified.
Will it be what you need.

**Comment by Vincz** [comment]
It would be great !

**Comment by halt-hammerzeit** [comment]
I added `http.url(path, is_server_side)` option in the latest version.
https://github.com/halt-hammerzeit/react-isomorphic-render#additional-react-isomorphic-renderjs-settings

**Comment by halt-hammerzeit** [comment]
FYI

```
6.1.0 / 23.10.2016
==================

  * Introduced `server_configuration.authentication.cookie` setting which sets authentication cookie name (if this setting is configured). If the authentication cookie exists then its value is assumed to be an authentication token and when using `http` utility in Redux actions this authentication token will be automatically sent along as part of `Authorization: Bearer {token}` HTTP header. If you were using a custom `http.url` formatter function (which is unlikely) then be aware that this authentication token can leak to a 3rd party if you don't restrict the allowed domains in your custom `http.url` formatter function.
```
