### ISSUE TITLE
Need to pass additional props to the router

### ISSUE THREAD

**Issue by Vincz** [halt-hammerzeit/react-isomorphic-render#17]
I'm using onUpdate method on the react-router (to hit analytics).
Currently, there is no way to pass additional properties to the router.
Maybe a new option would be great ? 
Something like this in the options:

    router: {
        props: {
            onUpdate: () => { analytics.hit(); }    
        }
    }

**Comment by halt-hammerzeit** [comment]
Is `onUpdate` needed only on the client side?

**Comment by Vincz** [comment]
Yes, i think, as there is no real route update on the server side...

**Comment by halt-hammerzeit** [comment]
Implemented in `5.0.0`.
```js
{
  on_navigate: (location) => ...
}
