### ISSUE TITLE
redux_middleware setting not working for page-server

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#2]
The redux_middleware option is not being respected on the server. I tracked it down, it is a simple naming bug:

page-server/render.js is expecting the option to be passed as 'redux_middleware' (line 17), but page-server/web server.js is passing it in as 'middleware' (line 155).

**Comment by halt-hammerzeit** [comment]
Oh, shoot, really.
I published `react-isomorphic-render@4.0.4` with the fix, try it out.

**Comment by adailey14** [comment]
Great it worked, thanks for the super fast update
