### ISSUE TITLE
IndexRedirect and Redirect not working, 'undefined' appended to all redirect locations

### ISSUE THREAD

**Issue by sorccu** [halt-hammerzeit/react-isomorphic-render#21]
Seems to be caused by `redirect_location.search` being always `undefined`. This:

```jsx
<Redirect from='/foo' to='/bar' />
```

causes redirect_location in `redux/render/render_on_server` to be:

```js
{ pathname: '/bar', query: { bar: null }, state: null }
```

When requested with `/foo?bar`. Leaving out the query string entirely does not change anything except `query` is an empty `{}`.

**Comment by halt-hammerzeit** [comment]
Yes, you found a bug.
I released a new version, try it out.

**Comment by sorccu** [comment]
While your commit does fix this particular issue, it seems that it is currently not possible to pass query parameters to the destination at all. Fortunately I don't need them right now, but is there any way we could get that to work as well? Out of interest I tried `require('url').format({ pathname: '/bar', query: { bar: null }, state: null })` earlier, but it produces `?bar=` as the search string, whereas it was originally just `?bar` without the `=`. So it wouldn't really be the original query.

**Comment by halt-hammerzeit** [comment]
I don't understand the `it seems that it is currently not possible to pass query parameters to the destination at all` issue.
If you can explain it by an example I could take a look.

**Comment by sorccu** [comment]
The new changes result in this behavior:

```
% curl -vvv 'http://localhost:3002/foo?a&b=c'
*   Trying ::1...
* Connected to localhost (::1) port 3002 (#0)
> GET /foo?a&b=c HTTP/1.1
> Host: localhost:3002
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 302 Found
< Location: /bar
< Content-Type: text/html; charset=utf-8
< Content-Length: 39
< Date: Mon, 10 Oct 2016 11:53:54 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
Redirecting to <a href="/bar">/bar</a>.
```

All query parameters are lost in the redirect.

**Comment by sorccu** [comment]
Correction: they were lost even before your change. However, I feel like both issues should be fixed right now if possible. However, I took a quick look at redux-router's source code, and I'm not sure if they're giving us the original, unparsed query at all. So it might be difficult.

**Comment by sorccu** [comment]
The intention of the original code clearly is to pass the query parameters. However that is not happening right now at all as far as I can see.

**Comment by halt-hammerzeit** [comment]
Well, it's working for me:

`http://127.0.0.1:3000/example/database?a=b`

```
<Redirect from='/example/database' to='/example/simple'/>
```

![screen shot 2016-10-10 at 15 09 19](https://cloud.githubusercontent.com/assets/477167/19235660/b6e66102-8efb-11e6-9694-8fc028d59028.png)

**Comment by sorccu** [comment]
I assume that's https://github.com/halt-hammerzeit/webapp. Doesn't it use `webpack-isomorphic-tools` for server side rendering?

**Comment by halt-hammerzeit** [comment]
Yes, it does

**Comment by sorccu** [comment]
Then it probably doesn't suffer from the same issue as `react-isomorphic-render`?

I think https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example would be more relevant as it uses `react-isomorphic-render`. You can see the same problem there:

```
% curl -vvv 'http://localhost:3000/example/database?a&b=c'
*   Trying ::1...
* connect to ::1 port 3000 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /example/database?a&b=c HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 302 Found
< location: /example/simpleundefined
< content-type: text/html; charset=utf-8
< content-length: 79
< date: Mon, 10 Oct 2016 12:25:37 GMT
< connection: close
<
* Closing connection 0
Redirecting to <a href="/example/simpleundefined">/example/simpleundefined</a>.
```

**Comment by halt-hammerzeit** [comment]
`webpack-isomorphic-tools` and `react-isomorphic-render` have nothing in common

**Comment by halt-hammerzeit** [comment]
`webpack-isomorphic-tools` doesn't know how to render anything

**Comment by sorccu** [comment]
Ok. Let's ignore webpack-isomorphic-tools since it's sidetracking the issue.

On a fresh clone of https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example, you should be able to see the same redirect issue I posted earlier. Is there any chance we could get redirects with query parameters working there?

**Comment by halt-hammerzeit** [comment]
Turned out `webpack-react-redux-isomorphic-render-example` had `4.x` dependency of `react-isomorphic-render` set in `package.json`.
I upgraded it to `5.x`.

The other bug seems to be in `react-router`:
```
@@@@@@@@@@@@@@ redirect_location { pathname: '/', query: { a: 'b' }, state: null }
```

It doesn't specify `search` parameter.
https://github.com/ReactTraining/react-router/blob/c3cd9675bd8a31368f87da74ac588981cbd6eae7/modules/createTransitionManager.js#L100

```
############# redirectInfo { pathname: '/', query: { a: 'b' }, state: null }
```

I filed a bug report in their repo
https://github.com/ReactTraining/react-router/issues/4023

**Comment by halt-hammerzeit** [comment]
Since they officially said that they aren't gonna fix this issue due to `react-router@2.x` branch support being dropped I implemented my own workaround.
So it's fixed in the new version.

**Comment by sorccu** [comment]
Thanks, looks great! There's one small issue remaining, I added a comment to your commit. Basically now redirects without any query parameters get `?` always appended to them.
