### ISSUE TITLE
Unnecessary modules in production builds

### ISSUE THREAD

**Issue by sorccu** [halt-hammerzeit/react-isomorphic-render#22]
Seems like [source/redux/store.js](https://github.com/halt-hammerzeit/react-isomorphic-render/blob/9a29264d8dc2f96155b2dfd4e188b70a53704129/source/redux/store.js) gets included for both client and server builds, in both production and development mode. Since it requires things like `redux-devtools`, `redux-router/server`, `history/lib/createMemoryHistory`, those get included in production builds as well, unnecessarily increasing bundle size. The application I'm working on is quite sensitive to file size, it would be great if we could find a way to not include these in production bundles.

You can verify the issue on a fresh clone of https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example, and then running `webpack --colors --display-error-details --config ./webpack/webpack.config.client.production.entry.js --display-modules`. If you look through the output, you'll see that it includes `redux-devtools` and other unnecessary dependencies.

It may be possible to work around the issue by using IgnorePlugin or an alias, I'll look into that next.

**Comment by halt-hammerzeit** [comment]
Yeah, I'll remove devtools dependency and will also split it into "client/server" imports

**Comment by halt-hammerzeit** [comment]
Try `react-isomorphic-render@6.0.0`.
Also you may have to rename a couple of options:

```
  * (breaking change) renamed `development_tools` to `devtools`, and it's now not just a React component but an object of shape `{ component, persistState }`
  * (breaking change) renamed `load_translation` to `translation`
  * (breaking change) renamed `on_error` to `catch` in server-side options
  * (breaking change) renamed `preload.on_error` option to `preload.catch`
```

**Comment by sorccu** [comment]
Wow that was fast... works great! Thanks again!
