### ISSUE TITLE
Optional/configurable reviver

### ISSUE THREAD

**Issue by sorccu** [halt-hammerzeit/react-isomorphic-render#23]
Definitely no offense meant in any way, but I'm one of those people who really care about the raw HTML output, and I find the `JSON.date_parser` snippet quite annoying to look at, especially since I don't even need it right now. I was wondering if it would be possible to do one of the following:

1. Make the reviver removable for apps that don't need it
2. Make the reviver snippet fully configurable so that it could either be completely removed or replaced with custom content

I'm kind of feeling that the reducer should take care of converting the initial state if necessary.

**Comment by halt-hammerzeit** [comment]
So, what you're talking about is to introduce an option for completely disabling `JSON.date_parser`?

**Comment by halt-hammerzeit** [comment]
Why would anyone not want Redux store dates to be recreated upon client-side reinitialization?

**Comment by halt-hammerzeit** [comment]
Well, ok, `Date` is not strictly a JSON value, so I introduced a common `parse_dates` option which can be set to `false`.

Also now removing `redux-router` data from Redux store when generating html page.
Seems to have no effect, so it's a bit cleaner.

**Comment by sorccu** [comment]
Thanks. I was thinking that if the reviver takes care of Dates already, perhaps it should be replaceable so that it could potentially take care of something else as well, like deserializing a custom class maybe? Anyway I don't have that need right now so it's more of a theoretical issue.
