### ISSUE TITLE
Make it easier to Upload Files through async middleware, or add this method to documentation?

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#26]
Just spent some time figuring out how to upload files through async middleware. It can be done like this:

```
export function myActionCreator(nonFileFields, fileList) {
  const fileObject = fileList[0];
  const formData = new FormData();
  _.each(nonFileFields, (key, value) => {
    formData.append(key, value);
  });

  formData.append('file', fileObject);

  return {
    events: [SUBMIT, SUBMIT_SUCCESS, SUBMIT_FAIL],
    promise: (client) => client.post('/submitUrl', formData)
  };
}
```

Superagent lets you do something like request.post('/myurl').attach('file', fileObject). Maybe there is a way to expose an attach option through your http_client to make it easier to upload files? So that the resulting code would be something like this instead:

```
export function myActionCreator(nonFileFields, fileList) {
  const fileObject = fileList[0];

  return {
    events: [SUBMIT, SUBMIT_SUCCESS, SUBMIT_FAIL],
    promise: (client) => client.post('/submitUrl', nonFileFields, { attach: { file: fileObject } })
  };
}
```

Or maybe there is even a way to just include File/FileList objects in the data passed to client and have it automatically attach them? So resulting code like this:

```
export function myActionCreator(allFieldsIncludingFiles) {
  return {
    events: [SUBMIT, SUBMIT_SUCCESS, SUBMIT_FAIL],
    promise: (client) => client.post('/submitUrl', allFieldsIncludingFiles)
  };
}
```

**Comment by halt-hammerzeit** [comment]
Sure, I can add `attach` option.
Not sure I understood your idea of automatically attaching files: how could it detect files?
Maybe it could do something like `if (data[key] instanceof ...)`?
Since you already have the code, you can nail it down: instance of what class is the file parameter should be.
Or should it detect if the whole `data` is `FormData` and then act accordingly?
But as per your first example it already can post `FormData` without issues.

**Comment by adailey14** [comment]
Yep using FormData works just fine, just took me some time digging to figure out how to do that. So just an enhancement idea, not a real "issue".

Yeah I was thinking to use instanceof to detect files or filelists (not sure which would be a cleaner api?)

When using redux-form (not the latest version) with <input type="file" {...field} />, I get passed a FileList object (since you can attach multiple files to a file input?). This code shows the response of instanceof:

```
// filesList comes from redux-form submit
console.log('What are Instances?', filesList instanceof FileList, filesList[0] instanceof File);
// this logs "true true"
```

I think you can attach multiple files with superagent for a single key like this:
request.post('/url').attach(key, [file1, file2]) where file1 and file2 are File objects
Maybe you can also attach a FileList directly, I don't know?
request.post('/url').attach(key, fileList)

**Comment by halt-hammerzeit** [comment]
Ok, I got you, I'll read `superagent` docs and will come up with something, maybe next day.

**Comment by adailey14** [comment]
Sounds good - no rush at all, I'm happily using FormData and things are good. It might also be cool to pipe file upload progress info back into the redux state somewhere so we could show progress bars. Just an idea...

**Comment by halt-hammerzeit** [comment]
Implemented in the newest version.
See https://github.com/halt-hammerzeit/react-isomorphic-render#ajax
