### ISSUE TITLE
Parse Dates caused unexpected bug

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#27]
Hi again! Sorry for all the issue reports.

I am passing a lot of data around in API calls, a lot of which includes some postgres database IDs. I'd never run into a problem before, but I guess today my IDs got into a certain numerical range where they started looking like dates? So they started getting parsed as dates and crashed many things.

I haven't looked at how the date parsing works, but it seems pretty dangerous if it can mistake database ids for dates. Anyway I turned off the parse dates option and now everything is working fine. Just thought I would let you know. Feel free to close this.

**Comment by halt-hammerzeit** [comment]
Oh.

Can you post the values which caused false positives?
I upldated the regexp recently to match broader value ranges.

**Comment by halt-hammerzeit** [comment]
Issue reports are better than their absence.
Have seen colleagues which preferred passing on using a library when they encountered a bug instead of reporting that bug in order for it to be discovered and fixed.

**Comment by halt-hammerzeit** [comment]
F*ck.
Yeah, perfect, it matches any four-digit number.
What a bug.
```
^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$
```
I'll fix that, narrow it down.

**Comment by adailey14** [comment]
I'm pretty sure in my particular case it was two database IDs that looked like this:
"75110"
"75111"

**Comment by halt-hammerzeit** [comment]
Fixed in the newest version.
Thx for the bug report, really missed this one.

**Comment by adailey14** [comment]
No problem! One other "bug" I've hit is if I include "<script>blah blah</script>" anywhere in my store I run into problems on the initial page load (html syntax error). I've gotten around this by escaping the strings I know will include this, and then unescaping them when I used them. Not sure if there would be a performant way to protect against this, maybe encoding the data passed from the server in some safe way. Let me know if you'd like more information.

**Comment by halt-hammerzeit** [comment]
Oh, I see, so it `JSON.stringify()`-es  the state, and if the state contains any html tags then it introduces an XSS vulnerability.
Good catch, thx.
I'll have to `escape_html()` everything inside `page-server/html.js` – no way around that.

**Comment by halt-hammerzeit** [comment]
Having read StackOverflow I came to a conclusion that a common way of escaping `<script/>` contents is by replacing every `</script` with `<\/script`:
http://stackoverflow.com/questions/14780858/escape-in-script-tag-contents
By the way, slashes can be safely escaped inside double quotes, so that would be an even more bullet-proof solution.
Like `"\/" === "/"`. Since this is the case, I'll be using this solution.
Yet another solution is to replace all slashes and angled brackets with unicode sequence symbols (like `\u00xx`)

**Comment by halt-hammerzeit** [comment]
(fixed)

**Comment by halt-hammerzeit** [comment]
Turns out I had a similar article open in my tabs for a couple of weeks, and have just decided to read it.
https://medium.com/node-security/the-most-common-xss-vulnerability-in-react-js-applications-2bdffbcc1fa0#.8dhdig4us
Exactly same issue

**Comment by adailey14** [comment]
Awesome! I'll try it out soon.
