### ISSUE TITLE
Secure application doesn't seem to work

### ISSUE THREAD

**Issue by kapakos** [halt-hammerzeit/react-isomorphic-render#29]
In the configuration for the web page server, when the application property secure is set to true it has no effect. The expectation is that the web server is available on https://localhost:3000. Am I missing something?

**Comment by halt-hammerzeit** [comment]
See the updated readme for the corrected description of the `secure` flag.

**Comment by halt-hammerzeit** [comment]
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/3d6f154a030e293c9de4599520becf82bff321d9/source/http%20client.js#L294

**Comment by halt-hammerzeit** [comment]
Oh, I now I get what you mean.
What you get out of the `react-isomorphic-render/page-service` function call is a Koa application.
It's then up to the developer whether to start it in HTTP or HTTPS:

```js
var http = require('http');
var https = require('https');
http.createServer(app.callback()).listen(3000);
https.createServer(options, app.callback()).listen(3001);
```

http://koajs.com/

Try that and tell me if it works.
