### ISSUE TITLE
Feature request - way to set headers in the http client

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#3]
This is a feature request.

Great work on this project and universal-webpack. I've been trying to migrate a project to use it today.

One thing I've run into that is stopping me is not having a way to hook into the http client when making api requests in order to add a header, while also having access to cookies server side. 

In our project currently we add an Auth header with a JWT (JSON web token) when making most requests to the api, and this is based on a value stored in a cookie. I can't figure out a way to do that using the react-isomorphic-render page-server currently.

I tried using my own middleware to do the api requests instead of the asynchronous middleware provided by default, but then I am not able to access cookies server side (which you are doing in the asynchronous middleware by passing the clone_request to the http_client).

So I think the best way to address this is to expand on the http_client api to allow header setting. Maybe just allow any key/value passed into the options hash to set headers on the superagent request?

Let me know what you think!

**Comment by halt-hammerzeit** [comment]
Oh, sure, I'll add the headers.

**Comment by halt-hammerzeit** [comment]
Yeah, used to spend quite some time figuring out how to make those cookies work, that was an uneasy task to grasp.

Anyway, I happen to have implemented custom headers already, in a separate library.
So I just copy & pasted the relevant code.
https://github.com/halt-hammerzeit/web-service/blob/master/source/http.js#L47-L53

Try `react-isomorphic-render@4.0.5`
Pass the third parameter `options` to `http` calls with `headers` object.
I didn't check it, so you tell me if it works.

**Comment by halt-hammerzeit** [comment]
Ok, so I thought that what you meant was not adding headers every time you make an HTTP request but rather set it up a single time and then apply it automatically.
So I took a different approach and introduced `http_request` parameter:

## Miscellaneous react-isomorphic-render.js settings

```javascript
{
  // (optional)
  // Extra HTTP request settings for `http` utility in Redux action creators
  // (`request` is a `superagent` request)
  http_request: request => request.set({ Authentication: `Bearer ${token}` })
}
```

This function will be called every time a request is made so you can adjust it based on some `if else` conditions.
If that's what you intended.

Or it could be a simple `headers` constructor parameter for `http_client` too.
Not as flexible though.

Try `react-isomorphic-render@4.0.6` and the new `http_request` setting.

**Comment by adailey14** [comment]
Yes that will work better, you're right the header options would only have
limited value if they could not be changed per request. I will check this
out tomorrow and let you know that everything works.

**Comment by halt-hammerzeit** [comment]
In `react-isomorphic-render@4.0.7` I have also added a second argument to `http_request` function holding a `store` because that data may be required.

```js

	http_request(request, { store })
	{
		console.log(request.headers)
		console.log(store.getState())
	}
```

**Comment by adailey14** [comment]
All of this is working well. The only problem left is accessing the cookie server side to check for a token and put it in the store. Can you think of a good way to do that?

Currently we are using react-cookie, and putting cookie.plugToRequest(req, res) in the server, then we could access the cookie anywhere on the server side or client side. Maybe you could add a hook somewhere to allow hooking things up to the req, res of the server?

**Comment by halt-hammerzeit** [comment]
Can you provide a pseudocode example?
I don't understand what you're describing here.

**Comment by adailey14** [comment]
Yes, maybe it will help if I describe the situation fully and you can tell me if there is a better way.

This is how my app handles authentication:
In App.js preload (top level route container) it dispatches an action called loadAuthCookie. This action checks if there is a cookie present with a saved token, and adds that token to the redux store. Any api requests that occur afterwards use add the token from the redux store to the Authorization header (now working thanks to the http_request hook you added).

The cookie token check needs to work on both client and server to allow rendering on the server to make authenticated api requests. This is accomplished using the react-cookie library, which makes a globally accessible cookie object, and can be plugged into the server request to grab the cookie on the server.

Here is code for my reducer:

import cookie from 'react-cookie';
import jwtDecode from 'jwt-decode';

// This function is called within reducer, logic could/should be moved to an action creator instead
function reduceLoadAuthCookie(state) {
  const token = cookie.load('token');
  const isAuthenticated = !!token;
  const hasAccount = token && jwtDecode(token).has_account;
  return {
    ...state,
    isAuthenticated,
    hasAccount,
    token,
  };
}


And this code is currently in my express web server (being replaced by the page-server from react-isomorphic-render):

import cookie from 'react-cookie';

app.use((req, res) => {
  cookie.plugToRequest(req, res);
  ...
  react-redux-router.match...
})


I am doing all of this because the api I'm working with doesn't accept cookies, it requires JWT authentication. Otherwise things would be ok since you are already copying the cookies from the original request into the api requests.

Let me know if that doesn't make sense I can clarify.

**Comment by halt-hammerzeit** [comment]
> I am doing all of this because the api I'm working with doesn't accept cookies, it requires JWT authentication

Fair enough.
The header is the standard, not the cookie.

I use the cookie too, but just for the browser and the server-side isomorphic counterpart.

Maybe what you're asking is how to read `authentication` cookie on the server side and then put it to the `store`?
You're doing it in the browser already, so you could do the same thing on the server-side.

There's a `preload` option for the webpage server:

```js
  // (optional)
  // Preloads data before performing page rendering.
  // If this function returns an object then this object
  // will be merged into Redux store.
  preload: async (http_client) => {}
  // (or same without `async`: (http_client) => Promise.resolve({})
```

You could get the cookie value there and then return something like `{ user: { token: true } }` (this data goes into Redux store).

Inspecting HTTP request cookies requires getting access to the HTTP request.
I can make a second parameter in that function: an object with `request` property which will be the original Node.js request.
Will that do?

**Comment by adailey14** [comment]
Yes you understand me and that would work perfectly, adding the 'request'
argument to 'preload'.

**Comment by halt-hammerzeit** [comment]
Try `react-isomorphic-render@4.0.8`

**Comment by halt-hammerzeit** [comment]
@adailey14 I'm planning on releasing an experimental caching solution for this library in the near future.
Are you using `preload` function parameter?
If yes, can you post it.
I'm planning to postpone `preload` function until the page is rendered: this way the results of `preload` won't be available until all `@preload()`s finish.

**Comment by halt-hammerzeit** [comment]
I mean, this thing will have to be changed:

```js
  http:
  {
    // (optional)
    // Will be called for each HTTP request
    // sent using `http` utility inside Redux action creators.
    // (`request` is a `superagent` request)
    request: (request, { store }) =>
    {
      const token = store.getState().authentication.token

      if (token)
      {
        request.set('Authorization', `Bearer ${token}`)
      }
    },
  }
```

Because `store.getState()` will be empty while server-side rendering is happening.

If you're using this approach then it should be changed.

For example, in the newest version it automatically sets the `Authorization` JWT header if the cookie is present (see HISTORY).
Will this functionality replace your existing preload token solution?

**Comment by adailey14** [comment]
Thanks for the heads up. I am using the preload parameter, maybe you can help me figure out where I can achieve the same things without it. I am using it to load information from the cookie and from the request into the store, which I use in a lot of places.

My preload parameter looks like this:
```
    preload: async (httpClient, { request }) => {
      // Merge authentication token into redux store if present

      const hostname = request.headers.host.replace(/:.*/, '');

      const cookies = cookie.parse(request.headers.cookie || '');
      const token = cookies.token;
      const isAuthenticated = !!token && token !== 'false';

      const useragent = request.headers['user-agent'];
      const mydevice = device(useragent);

      let mloId = null;
      if (isAuthenticated) {
        const decodedToken = jwtDecode(token);
        userId = decodedToken.user_id.toString();
      }

      return {
        authentication: {
          isAuthenticated,
          token,
          hostname,
          userId
        },
        device: {
          type: mydevice.type
        }
      };
    },
```

And my request parameter configuration currently looks like this:

```
    request: (request, { store }) => {
      const token = store.getState().authentication.token;
      const hostname = store.getState().authentication.hostname;

      if (token) {
        request.set('X-Auth', `Bearer ${token}`);
      }
      if (hostname) {
        request.set('X-Forwarded-For-Host', hostname);
      }
    }
```

**Comment by halt-hammerzeit** [comment]
Ok, we'll figure out the migration path.
In the meantime, the `store`'s `getState()` is used not only in the `request` parameter function but also in `@preload()` decorators.
I can see how `store.getState()` can be removed from your `request` parameter function.
What about your `@preload()` decorators: do you call `getState()` in any of them?

**Comment by halt-hammerzeit** [comment]
Or maybe you're reading `device` or `authentication` from state in any of your reducers. That could also matter.

**Comment by adailey14** [comment]
Hmm yes, I am using getState a lot in @preload decorators, and also in actionCreator "thunks" (some of which are called in @preload decorators). This is all done to access authentication info (isAuthenticated and  userId). For example I have a lot of api calls in the preload decorators that look something like this:

```
// root component preloader
const state = getState();
if (state.authentication.isAuthenticated) {
  loadUser(state.authentication.userId);
}
```
The device is only used for rendering, not needed for @preload decorators.

**Comment by halt-hammerzeit** [comment]
So, can we say that the only use case for `getState()` inside `@preload` in your project is getting `userId`?

**Comment by halt-hammerzeit** [comment]
Ok, seems that `getStore()` is gonna stay in the `@preload()` decorator.
Because it's justified to keep the user in the store.

**Comment by adailey14** [comment]
Yes, we can say that

**Comment by halt-hammerzeit** [comment]
Ok, I reasearched caching possibilities a bit and concluded that it's too advanced topic for now.
I guess I'll stick with Server Side Rendering each request for the time being while measuring performance.

As for the `7.0.0`, it has no radical changes in terms of being beneficial or such.
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/master/HISTORY.md
You can as well stay on `6.x` with your current set up as well.

`7.0.0` has a common `authentication` setting, which can be set up like this:

```js
{
  authentication:
  {
    cookie: 'token',
    header: 'X-Auth'
  }
}
```

That would automatically expand `token` cookie into `X-Auth` header when using `httpClient` (you'll still set `X-Forwarded-For-Host` header manually).
I'm not sure about the `token !== 'false'` piece though - this configuration doesn't handle this edge case in any way.

That's it for the caching topic for now.
If you get interested I summarised my research in a small document:
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/master/CACHING.md

**Comment by adailey14** [comment]
Cool thanks for sharing. I haven't really seen performance issues, because like you said: "since websites are Single Page Applications nowadays, all subsequent navigation will happen in the user's web browser and the page rendering server won't be involved."

I suspect some of the biggest performance gains with this architecture would come from using a CDN (like amazon cloudfront) to deliver the javascript / css / images instead of serving it from the same server doing the server side rendering. Do you know if there is any clever way to configure that with this project? It's been on my todo list for a while but haven't gotten to it yet.

**Comment by halt-hammerzeit** [comment]
Oh, yes, of course there is a way.
Don't know about being clever, but it's simply proxying everything with something like NginX or HAProxy.
The idea is same as per the README
https://github.com/halt-hammerzeit/react-isomorphic-render#server-side

* all HTTP GET requests starting with /assets return static files from your assets folder
* all HTTP requests starting with /api call your REST API methods (are proxied to API server)
* all the other HTTP GET requests are proxied to http://localhost:3000 for webpage rendering

All these three tasks can be handled by NginX, for example

```

 
    location /api {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
 
        rewrite ^/api/?(.*) /$1 break;
 
        proxy_pass http://api_node_js;
        proxy_redirect off;
    }
```

**Comment by adailey14** [comment]
Thanks for that. So when I've set up a CDN (amazon cloudfront) in the past, it works like this:

Configure the CDN to point to www.[mydomain].com. The CDN provides me a URL, like abcd.cloudfront.com.

I still serve my static assets from [mydomain].com/assets so the CDN can access them.

Configure my code to make all asset urls point to the CDN url, instead of my domain. So user visits www.[mydomain].com, and gets served html with tags like:
`<link href="https://abcd.cloudfront.com/assets/main-12345.css" rel="stylesheet" />`

So then the browser makes a request to the CDN domain, and the CDN checks its cache, and if the file is not there, it requests it from www.[mydomain].com/assets/main-12345.css, returns it to the request, and caches it for future requests.

When I've done this in Rails environment, there has been a way to set the CDN url in a gem somewhere and it will automatically use it in stylesheet links, javascript links, and other assets (maybe it was 2 different gems?). So I was thinking maybe there should be a way to do that in a react-isomorphic-render environment too.

Do you think there is a way to achieve what I am talking about using nginx configuration? Or would it require changing the asset urls?

**Comment by adailey14** [comment]
Here is an example of the kind of setup I did in rails: https://www.happybearsoftware.com/use-cloudfront-and-the-rails-asset-pipeline-to-speed-up-your-app.html

**Comment by halt-hammerzeit** [comment]
Well, they say that NginX (and other statics serving proxies) aren't required for CloudFront set up
https://www.peterbe.com/plog/is-nginx-obsolete-amazon-cloudfront

If a CDN is used, then yes, it would be justifiable to create a mechanism for replacing all links to the new ones pointing at that CDN.
For that purpose `output.publicPath` Webpack setting should be modified to point to the CDN root
https://github.com/webpack/docs/wiki/Configuration#outputpublicpath
And in conjunction with `universal-webpack`, I guess, that would be it.

**Comment by adailey14** [comment]
Ahh yes output.publicPath, seems like that's what I was looking for. Thanks!
