### ISSUE TITLE
Question about third party scripts for bodyEnd + node_modules

### ISSUE THREAD

**Issue by natdouglas** [halt-hammerzeit/react-isomorphic-render#30]
I'm using React-Intl, which requires script references in the HTML file.  Looking #25, I was able to get this working properly with the CDN references:

In code/page-server/web server.js
```
bodyEnd(url)
      {
        const addScripts=[];
        addScripts.push(<script key="react" src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.1/react.min.js" />);
        addScripts.push(<script key="reactIntl" src="https://cdnjs.cloudflare.com/ajax/libs/react-intl/1.2.2/react-intl.min.js" />);

        return addScripts;
      }

```

And I see the following for the resulting HTML:

> <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.1/react.min.js" data-reactroot="" data-reactid="1" data-react-checksum="-2039534981"></script>
> 
> <script src="https://cdnjs.cloudflare.com/ajax/libs/react-intl/1.2.2/react-intl.min.js" data-reactroot="" data-reactid="1" data-react-checksum="978398733"></script>

In my app code prior to webpack-react-redux-isomorphic-render-example, I used the node_module references directly in my index.html file (no server-side rendering) which worked:

>     <script src="../node_modules/react/dist/react.min.js"></script>
>     <script src="../node_modules/react-intl/dist/react-intl.min.js"></script>

I tried to use the node_module references with the webpack-react-redux-isomorphic-render-example boilerplate as follows:

```
      bodyEnd(url)
      {
        const addScripts=[];
        addScripts.push(<script key="react" src="../../node_modules/react/dist/react.min.js" />);
        addScripts.push(<script key="reactIntl" src="../../node_modules/react-intl/dist/react-intl.min.js" />);

        return addScripts;
      }
```

And I get the following for the resulting HTML:

> <script src="../../node_modules/react/dist/react.min.js" data-reactroot="" data-reactid="1" data-react-checksum="-27843881"></script>
> <script src="../../node_modules/react-intl/dist/react-intl.min.js" data-reactroot="" data-reactid="1" data-react-checksum="-2060048737"></script>

And the following console errors:

> react.min.js:1 Uncaught SyntaxError: Unexpected token <
> react-intl.min.js:1 Uncaught SyntaxError: Unexpected token <

Any ideas?  All help is appreciated as I'm LOVING react-isomorphic-render!

**Comment by halt-hammerzeit** [comment]
I'm using `react-intl` in my project too. Why aren't you bundling it as part of the main webpack bundle?

**Comment by halt-hammerzeit** [comment]
"node_module references" only work in HTML markup as long as they're served somehow.
They won't be magically available by HTTP.

**Comment by halt-hammerzeit** [comment]
`Uncaught SyntaxError: Unexpected token <` means that the file is not found and you're being served a "Page Not Found" HTML document instead of a javascript file.

**Comment by halt-hammerzeit** [comment]
So, my answer to this is:

* either require() react-intl in the code and it will be bundled ([like this](https://github.com/halt-hammerzeit/webapp/blob/c5887d746fe8de7c6cb4ba4d7aea16a5b723af74/frontend/code/wrapper.js))
* or include it in the `<head/>` from some kind of CDN like `npmcdn.com`

**Comment by natdouglas** [comment]
Gotcha. I'll look to bundling it as part of Webpack. Thanks.
