### ISSUE TITLE
Plug to be able to use alternate render functions with react-isomorphic render

### ISSUE THREAD

**Issue by animeshchat** [halt-hammerzeit/react-isomorphic-render#31]
We noticed that our renderToString function calls are taking too long (our page payload is large). 

Have you come across or tried react-dom-stream?

Is it possible to provide a hook to be able to use alternate render functions like react-dom-stream or react-ssr-optimization?

PS: Thanks for all the great work - we are using a lot of it.

**Comment by halt-hammerzeit** [comment]
Yes, if you use `stats` parameter you can see that it may take 100ms or more.
I have come around this issue by setting `render` to `false` because React SSR is not performant enough at the moment.
`react-dom-stream` was an interesting attempt but that project has been abandoned long time ago.
So, just set `render` to `false`.
Google bot can execute javascript, see the README

**Comment by halt-hammerzeit** [comment]
I'm gonna take a look at `react-ssr-optimization` though.
The issue with all those 3rd party tools is that eventually they get abandoned and new versions of React are released which are incompatible with them.
An official Facebook solution would be more appropriate.

**Comment by halt-hammerzeit** [comment]
`react-ssr-optimization` looks good.
And it's not abandoned yet.
So maybe I should add an extension point for it.

How the extension point would look like?

This goes to the `index.js`
```js
"use strict";

var componentOptimization = require("react-ssr-optimization");

var keyGenerator = function (props) {
    return props.id + ":" + props.name;
};

var componentOptimizationRef = componentOptimization({
    components: {
      'Component1': keyGenerator,
      'Component2': {
        cacheKeyGen: keyGenerator,
      },
    },
    lruCacheSettings: {
        max: 500,  //The maximum size of the cache
    }
});
```

No changes.
And, as per their readme, it should already work.
So seems that no extension point is even needed.
