### ISSUE TITLE
ReduxMiddleware

### ISSUE THREAD

**Issue by lamyat2005** [halt-hammerzeit/react-isomorphic-render#32]
Hi, I am trying apply redux-thunk however the reduxMiddleware seems not picked up. Would you please have a look? Thanks.

import thunkMiddleware from 'redux-thunk';
  // (optional)
  // User can add his own middleware to this `middleware` list
  reduxMiddleware: () => [thunkMiddleware]

**Comment by halt-hammerzeit** [comment]
Define "not picked up"

**Comment by halt-hammerzeit** [comment]
Have just tried it in my project and it worked

**Comment by lamyat2005** [comment]
Sorry my mistake, thanks.
