### ISSUE TITLE
Custom html template

### ISSUE THREAD

**Issue by saturito** [halt-hammerzeit/react-isomorphic-render#33]
Hello,

I need to use a custom html template for serving the pages, is this possible?

**Comment by halt-hammerzeit** [comment]
What makes it custom?

**Comment by saturito** [comment]
It is a very large template that comes from a CMS and it needs to be fetched on every request.

**Comment by halt-hammerzeit** [comment]
The only possibility to use a custom template is through the `html.head`, `html.bodyStart` and `html.bodyEnd` parameters (see the README)

**Comment by saturito** [comment]
You should consider this option

**Comment by halt-hammerzeit** [comment]
No, I guess I won't

**Comment by saturito** [comment]
and your bad attitude :)

**Comment by halt-hammerzeit** [comment]
Oh and you could stop judging people by your own standards as well. Or do you think the world must be the way you want it to be just because you want it to?
