### ISSUE TITLE
Usage with Radium

### ISSUE THREAD

**Issue by ksmandersen** [halt-hammerzeit/react-isomorphic-render#34]
I've been looking into using Radium in my codebase which is based of https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example. It's pretty easy to get set up until you get to the SSR part where Radium uses the User-Agent to generate vendor prefixed CSS. 

The way the suggest to configure Radium is to pass a radumConfig from the outer-most react component which here is the Wrapper. I don't see a way that is possible here. Maybe I am missing something.

Or maybe it is ill-advised to use Radium in this kind of setup?

**Comment by halt-hammerzeit** [comment]
Be more specific on what do you want to do

**Comment by halt-hammerzeit** [comment]
Closing due to being incomplete.
Reopen in case of a more descriptive description.
