### ISSUE TITLE
Using react-router-redux

### ISSUE THREAD

**Issue by lamyat2005** [halt-hammerzeit/react-isomorphic-render#37]
Hi, is there any way I can wrap history with syncHistoryWithStore ?
```
import {syncHistoryWithStore} from 'react-router-redux';

const history = syncHistoryWithStore(
    browserHistory,
    store,
  );
```

Thanks.

**Comment by halt-hammerzeit** [comment]
If someone wants `syncHistoryWithStore` then they could try to implement that.

Consider client-side:
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/master/source/redux/client/client.js#L44

There `history` is created and could be wrapped with `syncHistoryWithStore` right after.
But the `store` is created right after and it currently takes an already created `history` as an argument.

The store creation function doesn't use the `history` though so it could be replaced with something like `function get_history() { return history }`.
And also `history` would get replaced with `get_history()` in the two middlewares:
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/master/source/redux/middleware/history%20middleware.js
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/master/source/redux/middleware/preloading%20middleware.js

So, wrapping with `syncHistoryWithStore` could be done (on the client side).

As for the server side, `history` is created here:
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/master/source/page-server/render.js#L47

`store` is available there as `parameters.store` after the `await redux_initialize` call.

So it seems that the wrapping can be done both on client and server.

So if one forks this project, performs the changes, tests it both with javascript enabled and javascript disabled, and in case that works as intended I would think on a new configuration parameter like `history.wrap`.

**Comment by halt-hammerzeit** [comment]
I was thinking about making this change.
Have you started already?

**Comment by lamyat2005** [comment]
Not yet, much appreciated!

**Comment by halt-hammerzeit** [comment]
Released `react-isomorphic-render@10.2.0`.
Didn't check it so you're gonna be the beta-tester.
Seems to work.

**Comment by halt-hammerzeit** [comment]
```js

  // (optional)
  history:
  {
    // (optional)
    // `history` options (like `basename`)
    options: {}

    // (optional)
    // Custom `history` wrapper, like `syncHistoryWithStore` from `react-router-redux`
    wrap: (history, { store }) => history
  }

```

**Comment by lamyat2005** [comment]
However one more thing is in order for `react-router-redux` to work, need to add
```
import {routerMiddleware} from 'react-router-redux';

const middleware = [
    routerMiddleware(history),
];

applyMiddleware(...middleware)(createStore)(reducers, initialState);
```

I am not sure in `react-isomorphic-render.js`

```
reduxMiddleware: () => [routerMiddleware(history)],
```

how I can get `history`? Thanks very much in advance.

**Comment by halt-hammerzeit** [comment]
How do they pass `routerMiddleware(history)` to `createStore` when history itself needs `store` to be created in the first place as you described in your first post
