### ISSUE TITLE
Error response is not passed in asynchronous middleware

### ISSUE THREAD

**Issue by smalluban** [halt-hammerzeit/react-isomorphic-render#38]
Currently only message and status code from promise error is handled and passed to redux store. It should also pass response from server, which could be parsed later. 

In my application API sends some meaningful information when request is rejected. I checked and it is stored in `error.response` key, but `asynchronous middleware.js` is only using `error.data`, but it is undefined.

**Comment by halt-hammerzeit** [comment]
According to the code if the response is really a JSON then it's stored inside `error.data` and is not discarded:

```js
								switch (response.type)
								{
									// Set error `data` from response body,
									case 'application/json':
										// if (!is_object(error.data))
										error.data = get_response_body(response, parse_json_dates)

										// Set the more meaningful message for the error (if available)
										if (error.data.message)
										{
											error.message = error.data.message
										}

										break

							// HTTP request failed with an `error`
							return reject(error)
```

```js
					const error_data = is_object(error.data) ? error.data : {}

					if (!exists(error_data.message))
					{
						error_data.message = error.message
					}

					if (!exists(error_data.status))
					{
						error_data.status = error.status
					}

					// Dispatch the `failure` event to the Redux store
					dispatch
					({
						...rest,
						error : error_data,
						type  : Failure
					})
```

**Comment by smalluban** [comment]
Right, thanks for fast reply. I checked API endpoint and it responses with `application/vnd.api+json` `Content-Type`, which is not covered in condition. It is a header for JSON API specification. 

The problem is that, I really can not force API owner to change content-type header to `application/json`. It would be great to add this case.

**Comment by halt-hammerzeit** [comment]
Added in `react-isomorphic-render@10.3.4`
