### ISSUE TITLE
Question about redirecting in preload

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#39]
For an authentication use case, I want to check if a user is authenticated when navigating to a certain page (like the "onEnter" hook in react-router). I've seen you make some references in your documentation that you can use preload in place of onEnter, which seems ideal. But I'm trying to figure out if I'm doing the redirection correctly, given how the preload function returns a Promise and I'm not clear if redirect is synchronous or asynchronous.

So I am doing something like this:

```js
import { preload, redirect } from 'react-isomorphic-render';

@preload(({ dispatch, getState }) => {
  const { authentication } = getState();
  if (authentication.isAuthenticated) {
    // redirect the user to their dashboard if already logged in
    dispatch(redirect('/dashboard/'));
  }
  return Promise.resolve();
})
export default class Login extends Component {
  [... my Login component]
}
```

My question is - is that the right idea for server-side rendering? Should I be returning Promise.resolve() like that, or instead returning something else to ensure the redirect is happening server side? Everything seems to work this way but just wanted to check. Thank you!

**Comment by halt-hammerzeit** [comment]
I'd write it as `return dispatch(redirect('/dashboard/'));`
Other that that looks ok.

**Comment by adailey14** [comment]
Ok perfect, thanks!
