### ISSUE TITLE
http client 'put' uses query string

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#4]
Usually I send a 'put' with data using superagent's send method like this: request.send(data). You are using request.send(data) for 'post', but not for 'put' or 'patch', you are using request.query(data) instead. I'm not 100% sure but I think you should use send for 'put' and 'patch'.

In my case using the query parameter for 'put' serializes some objects that breaks communication with the api.

**Comment by halt-hammerzeit** [comment]
Oh, that's true.
Try `react-isomorphic-render@4.0.9`.

**Comment by adailey14** [comment]
Thanks! Your response time is unbelievable. 

FYI everything is going great with migrating my code to this library and universal-webpack. 

One snag is I am sometimes hitting a weird race condition when I start up in development mode, where I think node is trying to start when my /build/server.js file is not fully written, and I end up with an error like "your server.js file must output a function". When this happens I just kill it and restart and it goes away. I'd say it happens 1 out of 5 times. I will investigate it further later, but let me know if that's something you've seen too or if you have an idea how to fix it.

**Comment by halt-hammerzeit** [comment]
Well, maybe that's because I don't have a girlfriend and also I got unemployed past week so just chilling here all day long.

I never happened to have the race condition you described.
`your server.js file must output a function` means that it exports something and is found on disk, but the exported thing is not a function.
I've added a bit of extra console.log in `universal-webpack@0.1.23` so you may update for future cases.

**Comment by adailey14** [comment]
Haha that is too funny, I'm sorry to hear that about the girlfriend and job. Surely that situation won't last very long.

I got the error again with the new logging - I'm not sure if it's too illuminating:

```
Error: [universal-webpack] Your server source file must export a function. Got {}
    at /Users/andrewdailey/Code/mortgagehipporeact/node_modules/universal-webpack/source/server.js:62:9
    at run (/Users/andrewdailey/Code/mortgagehipporeact/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /Users/andrewdailey/Code/mortgagehipporeact/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/Users/andrewdailey/Code/mortgagehipporeact/node_modules/core-js/library/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[nodemon] app crashed - waiting for file changes before starting...
```

The server.js file is present, and is very large (4.91MB). If I kill the process and just run development-page-server, it still gives the error, so maybe it's not a race condition like I said before. Hmm I tried saving the server.js file and re-running the compilation and compared the files. They are identical. I restored the old file and now it worked - so perhaps it is something unrelated to the file itself. I will keep investigating to see if I can figure it out.

**Comment by halt-hammerzeit** [comment]
Update your `universal-webpack`: it's common for me to release a dozen of versions a day, haha.
I replaced console.log with node.js inspect, so it'll give more info now.

**Comment by halt-hammerzeit** [comment]
And, next time you catch that error also attach your `server.js` file so that it could be inspected.

**Comment by adailey14** [comment]
Ok I will do - I've just run the build 10 times in a row and I can't trigger the error. I'll be watching for it and let you know.
