### ISSUE TITLE
Where to Autohydrate Store for Redux?

### ISSUE THREAD

**Issue by weatherfordmat** [halt-hammerzeit/react-isomorphic-render#40]
I am enjoying this library, but am having difficulty figuring out the syntax for adding a store enhancer. It looks like it's simple to add new middleware, but I am thinking of adding redux-persist. 

Where would I do this?

I need to add the autoRehydrate() function to the enhancer, and I assume this is done in the application.js file or the react-isomorphic-render.js file.

```render(settings, {})
        .then(({ store, rerender }) => {
// begin periodically persisting the store;
// add autoRehydrate as enhancer
// call persistState(store);
  if (module.hot)
  {
    module.hot.accept('./react-isomorphic-render', () =>
    {
      store.hotReload(settings.reducer)
      rerender()
    })
  }
})```

**Comment by halt-hammerzeit** [comment]
Try the newest release.
https://github.com/halt-hammerzeit/react-isomorphic-render/commit/4afc476f8bfe6937ab1a56c1f6d49b2a190f0b53
See `reduxStoreEnhancers` function parameter.
I didn't test it.

**Comment by weatherfordmat** [comment]
Just finished testing this, and works well. Thank you.
