### ISSUE TITLE
Http Error with error handler triggers event undefined

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#41]
In the latest version (11.0.3) I am seeing this error:

```
TypeError: Cannot read property 'preloading' of undefined
    at asynchronous middleware.js:130
```

Looks to be triggered by this line, where event is undefined:
`if (!server && on_error && !event.preloading) {`

This is coming from dispatching an action creator that looks like this:
```
// I've simplied this - I am doing some logic after the dispatch. Wanted to show you that I am using thunk middleware here to dispatch the event - maybe that messes with the order of things?
export function login(email, password) {
  return (dispatch) => dispatch({
    events: [LOGIN, LOGIN_SUCCESS, LOGIN_FAIL],
    promise: client => client.post('/api/auth/authenticate_mlo/', {
      email,
      password
    })
  });
}
```

The server is responding with a 400 error with a response body like this:
{"errors":{"base":["Invalid username / password combination"]}}

And I have http.error defined in react-isomorphic-render like this:
```
  http: {
    error: (error, { redirect }) => {
      console.log('HTTP ERROR', error);
      if (error && (error.status === 401 || error.status === 403 || error.status === 419)) {
        return redirect('/logout');
      }
    }
  },
```

Not sure, but maybe event is undefined because I'm dispatching the action with events from thunk middleware?

**Comment by halt-hammerzeit** [comment]
Hmm, any thoughts why the `event` is `undefined`?

**Comment by halt-hammerzeit** [comment]
Oh, actually, there's no `event` variable at all.
Should be `action.preload`.
I'll correct that, supposedly that will resolve the issue.

**Comment by adailey14** [comment]
Sounds good, I will test it once you release the fix

**Comment by halt-hammerzeit** [comment]
Ok, try the new version (didn't test the error handler though)
