### ISSUE TITLE
Tiniest of documentation issues

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#44]
This line in the readme:

` localize: (store, preferredLocales) => ({ locale: preferredLocales[0], messages: { 'page.heading': 'Test' } })`

My observation is that the first argument to localize is a hash containing store, so the line should be like this:

` localize: ({ store }, preferredLocales) => ({ locale: preferredLocales[0], messages: { 'page.heading': 'Test' } })`

**Comment by halt-hammerzeit** [comment]
Oh, yes.
