### ISSUE TITLE
Make http_client use https protocol when port set to 443?

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#5]
I have an api which is accessed over https at port 443.

When I set options like this to react-isomorphic-render/page-server:

```js
  application:
  {
    host: 'myapi.com',
    port: 443
  },
```

It ends up making requests like this, which are failing:

http://myapi.com:443/api/blah

Should make requests like this:
https://myapi.com:443/api/blah

**Comment by halt-hammerzeit** [comment]
Try the latest version `react-isomorphic-render@4.0.15`:

```js
  application:
  {
    host: 'myapi.com',
    port: 443,
    secure: true
  },
```

**Comment by halt-hammerzeit** [comment]
Closed by https://github.com/halt-hammerzeit/react-isomorphic-render/commit/2eeedc7e01adb11073182c157b1376ed5bc24b53

**Comment by adailey14** [comment]
Perfect thanks
