### ISSUE TITLE
Redirect from within middleware

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/react-isomorphic-render#7]
I want to redirect from within my own middleware by dispatching 'goto', but it doesn't seem to work. I see within your code you do some hacky stuff to get around this in your preload middleware, but I don't have access to that in my middleware. Maybe you could apply the user supplied middleware 'before' applying reduxRouter store enhancer, but keep applying your preload middleware after it?

**Comment by halt-hammerzeit** [comment]
> I want to redirect from within my own middleware by dispatching 'goto'

How exactly

> but it doesn't seem to work

How exactly

**Comment by adailey14** [comment]
I wrote some middleware like this, that I pass in the redux_middleware parameter to react-isomorphis render:

```
import _ from 'lodash';

import { logout } from '../modules/authentication.js';
import { goto } from 'react-isomorphic-render/redux';

export default function logoutMiddleware() {
  return ({ dispatch, getState }) => next => action => {
    // Check for api errors related to authorization
    if (_.endsWith(action.type, '_FAIL')) {
      if (_.includes([419, 403, 401], action.error.status)) {
        console.log('TIME TO GO HOME', goto('/'));
        setTimeout(() => {
          dispatch(logout());
        }, 1000);
        dispatch(goto('/'));
      }
    }
    return next(action);
  };
}
```

When I watch the dispatched action, I only ever see the API_HISTORY action, but not ROUTER_CHANGED action. So the page doesn't actually change.

**Comment by halt-hammerzeit** [comment]
Which API_HISTORY action exactly do you see.

**Comment by halt-hammerzeit** [comment]
If there's no ROUTER_DID_CHANGE then it could be that API_HISTORY action never gets to historyMiddleware.

If you feel like editing raw javascript then you could add some `console.log`s to `node_modules/redux-router/lib/historyMiddleware` to get a peek inside the whole pipeline.

> I see within your code you do some hacky stuff to get around this in your preload middleware

I don't know about anything hacky there

**Comment by adailey14** [comment]
I see this one coming from the middleware:

```
{
  type:"@@reduxReactRouter/historyAPI",
  method:"push",
  args:
    0:"/"
}
```

When I dispatch goto from a component click for example, I see this action:
```
{
  type:"@@reduxReactRouter/routerDidChange",
  routes: ...
  params: ...
  location: ...
  components: ...
}
```

**Comment by adailey14** [comment]
By the "hacky stuff" I was referring to your comment in line 206 of preloading middleware.js:

Because `preloading_middleware` is `applied` to the store
before `reduxReactRouter` store enhancer adds its own middleware,
then it means that standard `dispatch` of `preloading_middleware`
won't send actions to that `reduxReactRouter` middleware,
therefore using this `dispatch_event` function to hack around that.

**Comment by halt-hammerzeit** [comment]
This action

```js
{
  type:"@@reduxReactRouter/historyAPI",
  method:"push",
  args:
    0:"/"
}
```

Means that a redirect is requested. When this action gets to `historyMIddleware` of `redux-router` then it does `history.push`.
Then a history listener (in `redux-router`) calls `routerDidChange()` which dispatches a ROUTER_DID_CHANGE action, which, upon arrival to the last middleware, renders the new route.

**Comment by halt-hammerzeit** [comment]
> By the "hacky stuff" I was referring to your comment in line 206 of preloading middleware.js

Oh, yes, Redux'es `createStore` gets called with the `middleware_chain`, and then another `createStore` gets called, and those are like independent layers with no peeking into each other. I guess, sort of. Maybe that's how Redux works.
Well, that could be a point.
I guess, that might be it: HISTORY_API action not being dispatched to `historyMiddleware` because it's in a different Redux layer.
So, what about that ROUTER_DID_CHANGE?
Post the full content of this action. Does it correspond to the HISTORY_API action? If it does, then this is not the "layers" thing.

**Comment by adailey14** [comment]
Yes that makes sense, but I think the dispatch being passed to the middleware is not connected to the redux-router history listener since the middleware is applied before the history listener is attached. I think that's what you are saying in that comment I pasted above.

**Comment by halt-hammerzeit** [comment]
> Yes that makes sense, but I think the dispatch being passed to the middleware is not connected to the redux-router history listener since the middleware is applied before the history listener is attached. I think that's what you are saying in that comment I pasted above.

Yes, that can be checked by inspecting that ROUTER_DID_CHANGE action.

**Comment by adailey14** [comment]
The ROUTER_DID_CHANGE event is not getting fired at all from the middleware. I was just posting it for reference - when things are working correctly, I see the ROUTER_DID_CHANGE action.

I think you are right about the redux layers thing, but I think 'inner' layers can access stuff from 'outer' layers. So if you run applyMiddleware(myMiddleware)(reduxReactRouter()(create_store)), then myMiddleware dispatch will hit the reduxRouter history listener. But if you run reduxReactRouter()(applyMiddleware(myMiddleware)(create_store)), then myMiddleware dispatched actions don't hit the listener.

However I don't think you can flip this for your preloadMiddleware, because that one is depending on the history event already being transformed by reduxRouter. But you could flip it for user supplied middleware. So end up with something like this:

applyMiddleware(preloadMiddleware, reduxReactRouter()(applyMiddleware(userMiddleware)(create_store)))

**Comment by halt-hammerzeit** [comment]
Yeah, I guess, that could be a viable idea...
Not so keen on all that "store enhancers" thing.

![](https://pbs.twimg.com/media/CdW4SMjWwAQMjrj.jpg:large)

I'll do some reading and also some experiments and post back

**Comment by adailey14** [comment]
Sounds good, great picture.

**Comment by halt-hammerzeit** [comment]
Ok, your proposed approach seems to be working.
Try the latest version.
`redux_middleware` now always takes an empty array, because that middleware is applied on a different level than preloading middleware.
I tested it in my sample project and `goto` worked for me.

**Comment by adailey14** [comment]
This is working great, thanks

**Comment by adailey14** [comment]
Hi Again,

There was an unintended side effect of this change, I will describe here.

Now when I dispatch actions from within a preload function (run by the preloading middleware during a route change), the dispatched actions do not hit my middleware provided in redux_middleware. I can fix this by changing line 232 of preloading middleware.js to use dispatch_event instead of dispatch, like this:

(current, dispatched events in preloader don't hit user middleware)
`const preload = preloader(server, components, getState, dispatch, location, params)`

(new, dispatched events in preloader do hit user middleware)
`const preload = preloader(server, components, getState, dispatch_event, location, params)`

I can't think of any reason not to make this change - but maybe you can.

Let me know what you think, thanks!

**Comment by halt-hammerzeit** [comment]
Oh, yeah, so tricky...
I've made the change you pointed out and I agree on this being a suitable solution.
Guess it will work now. Try the latest version.

**Comment by adailey14** [comment]
Hey Again,

So sorry to keep bothering you on this... but another slight issue with middleware composition.

When the asynchronous middleware is dispatching actions related to api calls (like GET_SOMETHING, GET_SOMETHING_SUCCESS, GET_SOMETHING_FAIL), those calls are not hitting the user defined middleware. I think this could be solved by either:

1. Passing in a dispatch_event argument to asynchronous middleware, the same way you do for preloading_middleware, and use that function for dispatching actions.
2. Apply the asynchronous middleware in the same place you are applying the user middleware. It doesn't depend on the reduxRouter stuff being loaded so that should be ok.

Let me know what you think...

**Comment by halt-hammerzeit** [comment]
Oh, another gotcha.
I think variant #1 is the most consistent one considering the workarounds
already implemented.
I'll release the fix when i get home

**Comment by halt-hammerzeit** [comment]
Oh, actually, turns out there is no `.dispatch()` in asynchronous middleware at all.
Everything is dispatched by calling `next(...)` which obviously just moves those events further the middleware chain, not though all the chain again.
I guess I'll substitute those `next(...)` calls with `dispatch_event`.

Try the new version, seems to be working.

**Comment by adailey14** [comment]
Thanks, this is working.

One more thing I found, that is tricky:

That logoutMiddleware I pasted in above in this thread ends up not working well within the server side render. The dispatch(goto('/')) call is throwing an error and expecting that error to bubble up to the top of the render function (see line 152 of redux/store.js in this project). 

But in my case I am calling dispatch(goto('/')) within the failure event of asynchronous middleware (see line 108 of asynchronous middleware.js). Since that call is already within a promise body, when it throws the redirect error, then I guess nothing happens (the promise neither resolves nor rejects). So the redirect doesn't happen and any code waiting on that promise never runs.

I'm not sure how to fix this, maybe instead of throwing an error, the redirect handlers could be hooked up directly to some redirection logic in render.

**Comment by halt-hammerzeit** [comment]
I have just tried creating a middleware with redirection on a certain _FAIL event and it worked for me.

```js

	redux_middleware(middleware)
	{
		return [({ dispatch, getState }) => next => action => {
			// Check for api errors related to authorization
		console.log('########### action', action)
			// if (action.events && action.events[0] === 'retrieving users') {
			if (action.type === 'deleting user failed') {
				console.log('~~~ deleting user failed ~~~')
				return dispatch(redirect('/logs'))
			}
			return next(action)
		}]
	},
```

Why aren't you returning after dispatching a redirect in your code?

**Comment by halt-hammerzeit** [comment]
Oh, that was client-side by the way.
Didn't test it on the server.
I'll try if it works for me on the server side.

**Comment by halt-hammerzeit** [comment]
@adailey14 Phew, okay, I managed to reproduce that.
Indeed, client-side worked as expected but server side didn't.
The cause was the `Promise` chain in `asynchronous_middleware`: it just didn't rethrow an error for some reason.
I rewrote that promise chain a little differently and now it works.
Try the latest version.

**Comment by halt-hammerzeit** [comment]
By the way, there's also `on_error` handler which you could possibly use alternatively to catching _FAILs in a middleware:

```js
// Is called when an error happens on the server side
  // (can redirect to special "500 Error" pages).
  // If this error handler is defined then it must handle
  // all errors it gets (or just re`throw` them).
  on_error: (error, { url, redirect }) => redirect(`/error?url=${encode(url)}&error=${error.code}`)
```

**Comment by halt-hammerzeit** [comment]
I meant this one:

```js
  // (optional)
  // Handles errors occurring inside `@preload()`.
  // For example, if `@preload()` throws a `new Error("Unauthorized")`,
  // then a redirect to "/unauthorized" page can be made here.
  // If this error handler is defined then it must handle
  // all errors it gets (or just re`throw` them).
  on_preload_error: (error, { url, redirect }) => redirect(`/error?url=${encode(url)}&error=${error.code}`)
```

**Comment by adailey14** [comment]
Thanks I will try it out. Yes I am using the on_preload_error, but I also want to catch any api errors I have after a page is loaded (for example if an authentication token expires while the page is open for a long time, and the user clicks a button that calls the api).

I know this was a tricky one, I was doing all of my testing on it on the client side and everything was fine, then got caught by the different redirect behavior on the server. Glad you were able to reproduce it.
