### ISSUE TITLE
Cannot read property 'getState' of undefined in routes.js

### ISSUE THREAD

**Issue by lamyat2005** [halt-hammerzeit/react-isomorphic-render#8]
I am trying to use onEnter, passing store as parameter in code/client/routes.js. However I see TypeError: Cannot read property 'getState' of undefined. Seems store is function getState() instead on initial loading.

Here is the code is code/client/routes.js:

```
export default function({store})
{
		console.log(store)
		const routes =
		(
			<Route
				component={RequireRole}
				onEnter={RequireRole.onEnter(store)}>
				<Route path="/" component={Layout} />
			</Route>
		)
	return routes
}
```

Thanks.

**Comment by halt-hammerzeit** [comment]
mm, that was a bug.
I fixed it, try the latest version.

And it will be like this now: (new, correct)
```
export default function(store)
``

As opposed to this: (old, incorrect)
```
export default function({ store })
```

Post back if it works now.
The `store` is not an actual store, but it has `dispatch` and `getState` if that's sufficient

**Comment by halt-hammerzeit** [comment]
Might as well write it as:

```
export default function({ dispatch, getState })
```

**Comment by lamyat2005** [comment]
Thanks.

On my first time call to store.getState() in RequireRole.onEnter, it says
store.js?9b69:92 Uncaught TypeError: Cannot read property 'getState' of undefined

I see store is undefined in first call in the react-isomorphic-render/build/redux/store :

`	// `redux-router` middleware
	// (redux-router keeps react-router state in Redux)
	reduxReactRouter({
		getRoutes: function getRoutes() {
			return create_routes({
				dispatch: function dispatch(action) {
					return store.dispatch(action);
				},
				getState: function getState() {
					// Here store is undefined
					return store.getState();
				}
			});
		},
`

Have I done something wrong after onEnter? Thanks.

**Comment by halt-hammerzeit** [comment]
It is undefined the first time because the store is created after the routes are created:

```
store = createStore(..., routes({ dispatch: (a) => store.dispatch(a), getState: () => store.getState() }))
```

You shouldn't nedd the store right away if you're using `store` in `onEnter`.

**Comment by lamyat2005** [comment]
I see you have new commits , is it related to the above? Thanks.

**Comment by halt-hammerzeit** [comment]
Yes, I added an error message so that a user won't be faced with `store is undefined`.

Does your code work?
Or are you still having issues?
