### ISSUE TITLE
Setting props on the created router

### ISSUE THREAD

**Issue by smspillaz** [halt-hammerzeit/react-isomorphic-render#9]
Currently the router is created from `source/redux/render` / `source/react-router/render`. I am transitioning some old code from react-redux-universal-hot-example which applies as `ReduxAsyncConnect` element as the `render` prop to `Router`.

It seems to me that there isn't any way to me to set props on the Router from its creation. The only object that gets to set the props is `store` from `transitionManager`.

**Comment by halt-hammerzeit** [comment]
`react-isomorphic-render` uses `redux-router` which doesn't use `<Router/>` element.
It uses `<RoutingContext/>` instead.
`<Router/>` element is not required, and all middleware can be applied directly to `<RoutingContext/>`.
https://github.com/reactjs/react-router/blob/0625e7656d21863563cf59019cfc16b800b79e85/upgrade-guides/v2.0.0.md#routingcontext---router-render-prop
https://github.com/reactjs/react-router/blob/master/modules/applyRouterMiddleware.js

Each property of `<Router/>` is passed down to `<RoutingContext/>`:
https://github.com/reactjs/react-router/blob/master/modules/Router.js#L172-L173

I could take some user defined options and pass them to the `<RoutingContext/>` being created.
But which properties exactly are you talking about and why.
If one previously used `ReduxAsyncConnect` to preload pages before rendering then `ReduxAsyncConnect` is replaced with `@preload` annotation (see the docs).
